from flask import Flask
app = Flask(__name__)
@app.route('/')
def home():
    return '''
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FOOTY PRO</title><style>*{margin:0;padding:0;box-sizing:border-box;font-family:system-ui}body{background:#0f1923;color:#fff;padding-bottom:80px}.top{background:#ffcc00;padding:10px;display:flex;justify-content:space-between;align-items:center}.logo{font-weight:900;color:#000}.bal{background:#000;color:#ffcc00;padding:6px 12px;border-radius:20px;font-size:11px;font-weight:800}.nav2{background:#1a2935;display:flex;gap:6px;padding:8px}.n2{padding:7px 14px;border-radius:20px;background:#253a4a;color:#aaa;font-size:12px;border:none}.n2.active{background:#fff;color:#000}.sub{display:flex;gap:6px;padding:8px}.s{padding:6px 14px;background:#1c2f3e;border-radius:6px;font-size:12px;color:#8aa1b5;border:none}.s.active{background:#00e676;color:#000}.match{background:#1a2935;margin:8px;border-radius:10px;overflow:hidden}.m-top{display:flex;justify-content:space-between;padding:6px 10px;font-size:10px;color:#8aa1b5;background:#16202b}.teams{padding:10px;font-weight:700}.odds{display:flex;gap:5px;padding:0 8px 8px}.od{flex:1;background:#253a4a;border-radius:6px;padding:10px;text-align:center;font-weight:800}.page{display:none}.page.active{display:block}.modal{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.85);display:none;z-index:50;align-items:center;justify-content:center;padding:15px}.modal.show{display:flex}.card{background:#1a2935;width:100%;max-width:360px;border-radius:12px;padding:18px}.card input{width:100%;padding:11px;background:#0f1923;border:1px solid #333;border-radius:8px;color:#fff;margin:6px 0}.avi-bg{background:#0a121a;height:220px;position:relative;border-radius:10px;margin:10px}.mult{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:42px;font-weight:900;color:#ffcc00}.plane{position:absolute;font-size:28px;bottom:40px;left:20px}.controls{display:flex;gap:8px;margin:10px}.cbox{flex:1;background:#1a2935;padding:10px;border-radius:10px}.h{display:flex;gap:5px;padding:8px;overflow-x:auto}.hi{padding:3px 7px;border-radius:10px;font-size:10px;font-weight:800}.low{background:#ff3b30}.mid{background:#ffcc00;color:#000}.high{background:#00e676;color:#000}</style></head><body>
<div class="top"><div class="logo">FOOTY PRO 2026</div><div style="display:flex;gap:6px"><div class="bal" id="bal">KES 0</div><button id="lb" onclick="openM('login')" style="border:none;border-radius:20px;padding:6px 12px;background:#000;color:#fff;font-weight:800">Login</button><button id="rb" onclick="openM('reg')" style="border:none;border-radius:20px;padding:6px 12px;background:#000;color:#fff;font-weight:800">Join</button><button id="ub" style="display:none;border:none;border-radius:20px;padding:6px 12px;background:#000;color:#ffcc00" onclick="logout()"></button></div></div>
<div class="nav2"><button class="n2 active" onclick="showP('soccer',this)">Soccer</button><button class="n2" onclick="showP('aviator',this)">Aviator</button><button class="n2" onclick="showP('account',this)">Account</button></div>
<div id="soccer" class="page active"><div class="sub"><button class="s active" onclick="filterD('today',this)">Today</button><button class="s" onclick="filterD('tomorrow',this)">Tomorrow</button><button class="s" onclick="filterD('live',this)">Live</button></div><div id="matches"></div></div>
<div id="aviator" class="page"><div class="h" id="hist"></div><div class="avi-bg"><div class="mult" id="mult">1.00x</div><div class="plane" id="plane">✈️</div></div><div class="controls"><div class="cbox"><input id="bet1" value="20" style="width:100%;padding:8px;background:#0f1923;border:1px solid #333;color:#fff;border-radius:6px;text-align:center"><button id="b1" onclick="placeB(1)" style="width:100%;margin-top:6px;padding:10px;background:#00e676;border:none;border-radius:6px;font-weight:900">BET</button></div><div class="cbox"><input id="bet2" value="50" style="width:100%;padding:8px;background:#0f1923;border:1px solid #333;color:#fff;border-radius:6px;text-align:center"><button id="b2" onclick="placeB(
